"""
Creation of the process run's initial record.

This module is the entry point for run tracking: it inserts a record with
status SCHEDULED into the process_run table and returns the run_id that the
whole subsequent run will use.
"""

import getpass
import socket
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from resources.database import get_session
from resources.models import ORMProcessRun
from resources.Schemas.process_run import ProcessRunStatus
from resources.settings import get_settings

_TZ = ZoneInfo('America/Fortaleza')


class AddProcessRun:
    """
    Responsible for creating the initial run record in the process_run table.

    It should be instantiated once at the start of every bot run. The run_id
    returned by execute() must be propagated to every module that needs to
    update the run's status.

    Example::

        run_id = AddProcessRun().execute()
        # run_id is now available for status updates

    """

    def execute(self) -> int:
        """
        Creates a new run record and returns its identifier.

        Returns:
            int: run_id of the created record (initial status: SCHEDULED).
        """
        return self.__create_process_run()

    @staticmethod
    def __create_process_run() -> int:
        """
        Inserts the ORMProcessRun record into the process_run table.

        It captures the machine's hostname and the operating-system user
        automatically, giving traceability with no manual configuration.

        Returns:
            int: run_id generated by the database.
        """
        settings = get_settings()

        now = datetime.now(_TZ)

        # Assignment by property instead of kwargs on the constructor:
        # ORMProcessRun's __init__ is generated at runtime by SQLAlchemy and
        # Pyright cannot inspect it, producing false "No parameter named X".
        process_run: Any = ORMProcessRun()
        process_run.process_name = settings.PROJECT_NAME
        process_run.resource_name = socket.gethostname()
        process_run.scheduled_by = getpass.getuser()
        process_run.area = settings.AREA
        process_run.status = ProcessRunStatus.SCHEDULED.value
        # autoload_with does not pick up PostgreSQL's DEFAULT now() on its own,
        # so the timestamps are supplied explicitly to avoid NotNullViolation
        process_run.created_at = now
        process_run.updated_at = now

        with get_session() as session:
            session.add(process_run)
            # flush sends the INSERT to the database without ending the
            # transaction, allowing the generated run_id to be read before the
            # context manager's implicit commit
            session.flush()
            run_id = process_run.run_id

        return run_id
