"""
Main orchestrator of the RPA Challenge run.

Responsibilities:
- Record the start and the end of the run in the process_run table.
- Load the input data (XLSX).
- Start the browser and run the form filling.
- Make sure the status in the database reflects what actually happened, either
  COMPLETED on success or FAILED with the error details.
"""

import traceback

from botcity.maestro import BotMaestroSDK

from resources.Drivers.factory import create_driver, resolve_driver
from resources.Executors.execute_challenge import read_data, run_challenge
from resources.models import ProcessRunStatus
from resources.settings import get_settings
from resources.Tools.add_process_run import AddProcessRun
from resources.Tools.botcity import (
    Counts,
    get_task_parameters,
    report_completion,
    report_failure,
)
from resources.Tools.logs import Logs
from resources.Utils.create_items import create_items
from resources.Utils.operation_db import OperationDb


class Execute:
    """
    Class responsible for orchestrating the entire bot run.

    The constructor already creates the run record in the database with status
    SCHEDULED, giving traceability from the instant the process starts.

    Attributes:
        maestro: BotCity SDK for integration with the automation server.
        logs: Combined logger (console, file and database).
        settings: Settings loaded from config.json.
        db: Facade for the database operations on process_run and item_run.
        run_id: Unique identifier of this run, generated by the database at
            startup.
    """

    def __init__(self, maestro: BotMaestroSDK, driver: str | None = None):
        """
        Args:
            maestro: SDK already initialised by the entry point. It arrives
                ready-made rather than being created here, so as not to open a
                second connection to the orchestrator — bot.py needs the SDK
                before this class exists, in order to report startup failures.
            driver: 'playwright' or 'selenium', coming from the command line.
                Omitted, the driver is decided in three layers — see
                Drivers.factory.resolve_driver.
        """
        self.maestro = maestro
        task_parameters = get_task_parameters(maestro)

        self.logs = Logs(self.maestro)
        self.settings = get_settings()
        self.chosen_driver = resolve_driver(driver, task_parameters)

        # With no command-line argument, a chosen driver can only have come
        # from the task parameter - and recording where it came from spares
        # whoever investigates from checking three places to learn why that
        # driver ran.
        if self.chosen_driver and not driver:
            self.logs.info(f'Driver set by the task parameter: {self.chosen_driver}.')

        self.db = OperationDb()

        # Creates the initial record in the database; from here on, run_id
        # identifies this run across every related table
        self.run_id = AddProcessRun().execute()
        self.logs.info(
            f'Run recorded in the database with run_id={self.run_id} (SCHEDULED)'
        )

    def execute(self) -> None:
        """
        Runs the complete RPA Challenge flow.

        Flow:
            1. Update process_run to RUNNING.
            2. Read the data from the input XLSX file.
            3. Persist the data into the item_run and item tables (QUEUED).
            4. Read from the database the items ready for processing.
            5. Open the browser and run the form filling, updating each item's
               status in the database.
            6. Update process_run to COMPLETED on success.
            7. On any exception, update it to FAILED with message and stack
               trace, and re-raise the error.
        """
        self.db.update_process_run_status(self.run_id, ProcessRunStatus.RUNNING)
        self.logs.info(f'run_id={self.run_id} → RUNNING')

        total = 0
        result = ''
        driver_name = self.chosen_driver or self.settings.DRIVER

        try:
            # Reads the Excel file and persists item_run + item in the database
            data = read_data(self.logs)
            item_ids = create_items(data, self.run_id)
            self.logs.info(f'{len(item_ids)} items persisted to the database (QUEUED).')

            # Reads from the database the items ready for processing
            items = self.db.get_queued_items_by_run(self.run_id)
            total = len(items)
            self.logs.info(f'{total} items loaded from the database for processing.')

            # Visible window: the operator watches the bot filling the form.
            driver = create_driver(self.chosen_driver, headless=False)
            driver_name = driver.name
            self.logs.info(f'Driver selected: {driver.name}.')
            try:
                result = run_challenge(
                    driver, self.logs, items, self.settings.PATH_URL, self.db
                )
            finally:
                # A failure to close becomes a warning: masking the original
                # error with a cleanup problem would send the diagnosis to the
                # wrong place.
                try:
                    driver.close()
                except Exception as cleanup_error:
                    self.logs.warning(f'Failed to close the browser: {cleanup_error}')

            self.db.update_process_run_status(self.run_id, ProcessRunStatus.COMPLETED)
            self.logs.info(f'run_id={self.run_id} → COMPLETED')

            processed, failed = self.db.count_completed_and_failed(self.run_id)
            report_completion(
                self.maestro,
                Counts(total, processed, failed),
                driver_name,
                result,
            )

        except Exception as e:
            # Captures the full stack trace for diagnosis in the database
            stack = traceback.format_exc()
            self.db.update_process_run_status(
                self.run_id,
                ProcessRunStatus.FAILED,
                error_message=str(e),
                error_stack=stack,
            )
            self.logs.error(e)
            self.logs.info(f'run_id={self.run_id} → FAILED')

            # This query runs while we are already trying to report another
            # exception: letting it surface would mask the original problem,
            # which is the one that matters.
            try:
                processed, failed = self.db.count_completed_and_failed(self.run_id)
            except Exception as query_error:
                self.logs.warning(f'Could not count the items: {query_error}')
                processed = failed = 0

            report_failure(
                self.maestro,
                e,
                Counts(total, processed, failed),
                driver_name,
            )
            raise
