"""create item_run and item tables

Revision ID: 3da4bd0b1cc6
Revises: 
Create Date: 2026-05-11 10:22:11.879153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3da4bd0b1cc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_run',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXCEPTION', 'ON_HOLD', 'DEFERRED', name='item_run_status', schema='rpa_challenge'), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_work_time', sa.Interval(), nullable=True),
    sa.Column('exception_at', sa.DateTime(), nullable=True),
    sa.Column('exception_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['process_manager.process_run.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    schema='rpa_challenge'
    )
    op.create_index(op.f('ix_rpa_challenge_item_run_run_id'), 'item_run', ['run_id'], unique=False, schema='rpa_challenge')
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(), nullable=False),
    sa.Column('Last_Name', sa.String(), nullable=False),
    sa.Column('Company_Name', sa.String(), nullable=False),
    sa.Column('Role_in_Company', sa.String(), nullable=False),
    sa.Column('Address', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Phone_Number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['rpa_challenge.item_run.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rpa_challenge'
    )
    op.create_index(op.f('ix_rpa_challenge_item_item_id'), 'item', ['item_id'], unique=False, schema='rpa_challenge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpa_challenge_item_item_id'), table_name='item', schema='rpa_challenge')
    op.drop_table('item', schema='rpa_challenge')
    op.drop_index(op.f('ix_rpa_challenge_item_run_run_id'), table_name='item_run', schema='rpa_challenge')
    op.drop_table('item_run', schema='rpa_challenge')
    # ### end Alembic commands ###
