"""
Creation of the item_run and item records from the input file's data.

For every row of the DataFrame it inserts an item_run with status QUEUED and an
item holding the form data, both tied to the run_id of the current run.
"""

import socket
from typing import Any

import pandas as pd

from resources.database import get_session
from resources.models import ItemRunStatus, ORMItem, ORMItemRun
from resources.settings import get_settings


def create_items(data: pd.DataFrame, run_id: int) -> list[int]:
    """
    Persists the DataFrame's data into the item_run and item tables.

    For each row it creates an item_run (QUEUED) and an item with the form
    fields. The flush after each item_run guarantees that the item_id generated
    by the database is available as a foreign key on ORMItem.

    Args:
        data: DataFrame with the data read from the input file.
        run_id: Identifier of the current process, generated by AddProcessRun.

    Returns:
        list[int]: List of the item_ids created.
    """
    settings = get_settings()
    item_ids: list[int] = []

    with get_session() as session:
        for _, row in data.iterrows():
            item_key = f'{row["First Name"]}_{row["Phone Number"]}'

            # SQLAlchemy decorates mapped_as_dataclass with @dataclass_transform,
            # but neither type checker acts on it: mypy reveals __init__ as
            # `def (self: object)` for a twelve-line class with nothing from this
            # project in it, so every field reads as an unexpected keyword. The
            # constructor is generated at runtime and works. add_process_run.py
            # dodges the same limitation by assigning attributes one by one -
            # that is the alternative, and it is worse here, because these two
            # classes really are dataclasses.
            item_run: Any = ORMItemRun(  # type: ignore[call-arg]
                run_id=run_id,
                process_name=settings.PROJECT_NAME,
                item_key=item_key,
                area=settings.AREA,
                priority=0,
                status=ItemRunStatus.QUEUED,
                tags='',
                resource_name=socket.gethostname(),
                attempt=0,
            )
            session.add(item_run)
            # flush sends the INSERT without closing the transaction,
            # which allows reading item_id before the implicit commit
            session.flush()

            item: Any = ORMItem(  # type: ignore[call-arg]
                item_id=item_run.item_id,
                First_Name=str(row['First Name']),
                Last_Name=str(row['Last Name']),
                Company_Name=str(row['Company Name']),
                Role_in_Company=str(row['Role in Company']),
                Address=str(row['Address']),
                Email=str(row['Email']),
                Phone_Number=str(row['Phone Number']),
            )
            session.add(item)
            item_ids.append(item_run.item_id)

    return item_ids
