"""
Database operations for the process_run table.

At this first stage the module exposes only the operations needed to track the
life cycle of a process run:
- insert_process_run: creates a new record (rarely used directly; prefer
  AddProcessRun for the initial creation).
- update_process_run_status: updates status, timestamps and errors according to
  the state transition.

Supported status transitions:
    SCHEDULED → RUNNING   : fills started_at and stage_started_at
    RUNNING   → COMPLETED : fills ended_at and computes total_work_time
    RUNNING   → FAILED    : fills ended_at, total_work_time, error_message
                            and error_stack
    any       → CANCELED  : fills ended_at and total_work_time
"""

from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from sqlalchemy import func, select
from sqlalchemy.exc import NoResultFound

from resources.database import get_session
from resources.models import ItemRunStatus, ORMItem, ORMItemRun, ORMProcessRun
from resources.Schemas.item_run import Item, ItemInfo, ItemRun
from resources.Schemas.process_run import ProcessRun, ProcessRunStatus

# Default timezone for every timestamp recorded in the database
_TZ = ZoneInfo('America/Fortaleza')


class OperationDb:
    """
    Database access facade for process_run operations.

    Every method is static: the class serves only as an organised namespace,
    with no internal state.

    Example::

        db = OperationDb()
        db.update_process_run_status(run_id=1, status=ProcessRunStatus.RUNNING)
    """

    # ─────────────────────────────────────────────────────────────────────────
    # process_run — insertion
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def insert_process_run(process_run: ProcessRun) -> int:
        """
        Inserts a new record into the process_run table.

        Prefer AddProcessRun.execute() for the initial creation of a process,
        since it already captures hostname and user automatically. This method
        is useful for advanced cases where the ProcessRun schema has already
        been assembled elsewhere.

        Args:
            process_run: Pydantic schema holding the process data.

        Returns:
            int: run_id generated by the database.
        """
        orm_run: Any = ORMProcessRun()
        orm_run.process_name = process_run.process_name
        orm_run.resource_name = process_run.resource_name
        orm_run.scheduled_by = process_run.scheduled_by
        orm_run.area = process_run.area
        orm_run.status = process_run.status

        with get_session() as session:
            session.add(orm_run)
            session.flush()
            run_id = orm_run.run_id

        return run_id

    # ─────────────────────────────────────────────────────────────────────────
    # process_run — status update
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def update_process_run_status(
        run_id: int,
        status: ProcessRunStatus,
        error_message: str | None = None,
        error_stack: str | None = None,
    ) -> None:
        """
        Updates a run's status and fills the timestamp fields according to the
        state transition.

        Behaviour per status:

        - **RUNNING**: sets started_at (if still None) and stage_started_at to
          the current moment; clears the error fields.
        - **COMPLETED**: sets ended_at and computes total_work_time; clears the
          error fields.
        - **FAILED**: sets ended_at, computes total_work_time and persists
          error_message and error_stack. When these are not supplied, it uses
          default messages so the record is never left empty.
        - **CANCELED**: sets ended_at and computes total_work_time.
        - **SCHEDULED**: only updates the status.

        Args:
            run_id: Identifier of the record to update.
            status: The run's new status (a ProcessRunStatus enum value).
            error_message: Human-readable error message (FAILED only).
            error_stack: Full error stack trace (FAILED only).

        Raises:
            NoResultFound: If no record exists with the given run_id.
            ValueError: If the supplied status is not valid.
        """
        now = datetime.now(_TZ)

        with get_session() as session:
            pr: Any = session.execute(
                select(ORMProcessRun).where(ORMProcessRun.run_id == run_id)  # type: ignore[attr-defined]
            ).scalar_one_or_none()

            if pr is None:
                raise NoResultFound(
                    f'ProcessRun with run_id={run_id} not found in the database.'
                )

            pr.status = status.value

            match status:
                case ProcessRunStatus.RUNNING:
                    # Preserves the original started_at if the process already
                    # started
                    if pr.started_at is None:
                        pr.started_at = now
                    pr.stage_started_at = now
                    # Makes sure errors from previous runs do not linger
                    pr.error_message = None
                    pr.error_stack = None

                case ProcessRunStatus.COMPLETED:
                    if pr.started_at is None:
                        pr.started_at = now
                    pr.ended_at = now
                    pr.total_work_time = pr.ended_at - pr.started_at.astimezone(_TZ)
                    pr.error_message = None
                    pr.error_stack = None

                case ProcessRunStatus.FAILED:
                    if pr.started_at is None:
                        pr.started_at = now
                    pr.ended_at = now
                    pr.total_work_time = pr.ended_at - pr.started_at.astimezone(_TZ)
                    # Never leaves the error field empty, to ease diagnosis
                    pr.error_message = (
                        error_message or 'Process failed with no error message.'
                    )
                    pr.error_stack = error_stack or 'Stack trace unavailable.'

                case ProcessRunStatus.CANCELED:
                    if pr.started_at is None:
                        pr.started_at = now
                    pr.ended_at = now
                    pr.total_work_time = pr.ended_at - pr.started_at.astimezone(_TZ)

                case ProcessRunStatus.SCHEDULED:
                    pass  # Only records the new status; no timestamp changes

            session.flush()

    # ─────────────────────────────────────────────────────────────────────────
    # item_run — querying and status update
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def get_queued_items_by_run(run_id: int) -> list[ItemInfo]:
        """
        Returns every item with status QUEUED for the given run.

        It joins process_run, item_run and item to assemble the complete
        ItemInfo, which run_challenge then uses to process each form and update
        the status in the database.

        Args:
            run_id: Identifier of the running process.

        Returns:
            list[ItemInfo]: Items ready for processing, ordered by item_id.
        """
        with get_session() as session:
            stmt = (
                select(ORMProcessRun, ORMItemRun, ORMItem)
                .join(ORMItemRun, ORMItemRun.run_id == ORMProcessRun.run_id)  # type: ignore[attr-defined]
                .join(ORMItem, ORMItem.item_id == ORMItemRun.item_id)
                .where(
                    ORMProcessRun.run_id == run_id,  # type: ignore[attr-defined]
                    ORMItemRun.status == ItemRunStatus.QUEUED.value,
                )
                .order_by(ORMItemRun.item_id)
            )
            rows = session.execute(stmt).all()
            return [
                ItemInfo(
                    process_run=ProcessRun.model_validate(pr),
                    item_run=ItemRun.model_validate(ir),
                    item=Item.model_validate(it),
                )
                for pr, ir, it in rows
            ]

    @staticmethod
    def count_completed_and_failed(run_id: int) -> tuple[int, int]:
        """
        Counts how many of the run's items completed and how many failed.

        It is the **source of truth** for the report sent to the orchestrator.
        In-memory counters stop being updated when a runtime failure interrupts
        the loop — a browser that dies, a site that goes down — and the panel
        would then receive zeros while the database already holds dozens of
        items recorded as COMPLETED. Here the number comes from where the state
        actually lives.

        Translating statuses into numbers happens here because this is the
        layer that knows about ItemRunStatus; the caller receives two integers
        and does not need to know how the state is represented.

        Args:
            run_id: Identifier of the run.

        Returns:
            tuple[int, int]: (completed, failed).
        """
        with get_session() as session:
            stmt = (
                select(ORMItemRun.status, func.count())
                .where(ORMItemRun.run_id == run_id)
                .group_by(ORMItemRun.status)
            )
            by_status = {status: amount for status, amount in session.execute(stmt)}

        return (
            by_status.get(ItemRunStatus.COMPLETED.value, 0),
            by_status.get(ItemRunStatus.FAILED.value, 0),
        )

    @staticmethod
    def update_item_run_status(
        item_id: int,
        status: ItemRunStatus,
        exception_reason: str | None = None,
    ) -> None:
        """
        Updates an item_run's status and fills the timestamp fields according
        to the state transition.

        Behaviour per status:

        - **PROCESSING**: sets started_at and last_updated_at.
        - **COMPLETED**: sets completed_at, last_updated_at and computes
          total_work_time.
        - **FAILED**: sets exception_at, exception_reason, last_updated_at and
          computes total_work_time.

        Args:
            item_id: Identifier of the item_run to update.
            status: The new status (an ItemRunStatus enum value).
            exception_reason: Error message (FAILED only).

        Raises:
            NoResultFound: If no item_run exists with the given item_id.
        """
        now = datetime.now(_TZ)

        with get_session() as session:
            ir: Any = session.execute(
                select(ORMItemRun).where(ORMItemRun.item_id == item_id)
            ).scalar_one_or_none()

            if ir is None:
                raise NoResultFound(
                    f'ItemRun with item_id={item_id} not found in the database.'
                )

            ir.status = status.value

            match status:
                case ItemRunStatus.PROCESSING:
                    ir.started_at = now
                    ir.last_updated_at = now

                case ItemRunStatus.COMPLETED:
                    ir.completed_at = now
                    ir.last_updated_at = now
                    if ir.started_at:
                        ir.total_work_time = now - ir.started_at.astimezone(_TZ)

                case ItemRunStatus.FAILED:
                    ir.exception_at = now
                    ir.last_updated_at = now
                    ir.exception_reason = exception_reason or 'Error with no message.'
                    if ir.started_at:
                        ir.total_work_time = now - ir.started_at.astimezone(_TZ)

            session.flush()

    @staticmethod
    def update_items_result(item_ids: list[int], result: str) -> None:
        """
        Writes the challenge's final result into each item's result column.

        Called after capture_result(), once the text shown by the challenge is
        available. The same result is recorded on every item of the run,
        because the RPA Challenge returns a single score for the whole run.

        Args:
            item_ids: List of item_ids (the FK on item) to update.
            result: The result text captured from the challenge page.
        """
        with get_session() as session:
            for item_id in item_ids:
                it: Any = session.execute(
                    select(ORMItem).where(ORMItem.item_id == item_id)
                ).scalar_one_or_none()
                if it is not None:
                    it.result = result
            session.flush()
